### ISSUE TITLE
our sexy site

### ISSUE THREAD

**Issue by rameramwe** [rameramwe/our-sexy-site#1]
check this out . @rawadtraboulsi

**Comment by rawadtraboulsi** [comment]
cool dude, i took a look, and here are few of my notes:

The code in client folder should be in server folder. 
Did you consider using plugins for accounts?

Did you set up a mongo database online somewhere? there are several free providers.

**Comment by rameramwe** [comment]
sorry i just saw this .... yeah i thought it should be in server folder haha
and no i didn't setup a mongo  database online  ...why should i do that ? 
and thanks for the awesome useful notes i'll take them under consideration and make a new version of the site using these notes .
